name: Stephen Kelly
highlighter: pygments
markdown: redcarpet
permalink: /:title

url: http://stephenjpkelly.com/
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed